# this is not live it is just a playlist...
Tracklist: original by Ezonater
00:00: - Internet Settings [Nintendo 3DS]
02:23: - A Starlit Sky [Mario Party 9]
05:28: - Introduction [Tomodachi Life]
06:43: - World 1/2 [Super Mario Galaxy 2]
08:53: - Mario Kart Channel [Mario Kart 7]
09:55: - S.S. Drake [Pikmin 3]
12:50: - Café Petrov [Nintendogs + Cats]
16:29: - Bubbly Clouds [Kirby's Epic Yarn]
18:50: - Soaring the Sky (Night) [Pokémon ORAS]
22:03: - Dream Land [Kirby's Epic Yarn]
23:45: - Letter [Tomodachi Life]
25:53: - Pokémon League (Night) [Pokémon DPPt]
28:49: - Cove Area (Lookout) [PokéPark 2]
30:37: - Kirby's Pad [Kirby's Epic Yarn]
32:50: - Dock List [Tomodachi Life]
34:01: - Undella Town (Winter) [Pokémon BW]
37:13: - Sunflowers and Illusions [Mother 3]
39:59: - Main Theme [Nintendo eShop]
42:00: - Globe (Night) [Weather Channel]
47:33: - Wi-Fi Menu [Mario Kart 7]
50:19: - Main Menu EX [AR Games]
52:01: - Course World [Super Mario Maker 2]
53:18: - Underwater Passage [Super Mario Odyssey]
55:42: - BGM 3 [Mario Paint]
59:17: - Sky Land [New Super Mario Bros. Wii]
